# Generated by Django 5.2.4 on 2025-07-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0002_validacionuser_delete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validacionuser',
            name='contraseña',
        ),
        migrations.AlterField(
            model_name='validacionuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
